name: E2E Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and start
      run: |
        npm install
        npm run build --if-present
        npm start &
    - name: flow
      run: |
        npm run flow
    - name: cypress
      run: |
        npm run cypress:run
      env:
        CI: true
